#!/bin/bash
# ~/.config/eww/scripts/memory
# возвращает использование памяти в процентах

awk '/MemTotal/{total=$2} /MemAvailable/{available=$2} END{printf "%.0f", (total-available)/total*100}' /proc/meminfo
