#┏━╸┏━╸┏┓╻┏━╸┏━┓┏━┓╻
#┃╺┓┣╸ ┃┗┫┣╸ ┣┳┛┣━┫┃
#┗━┛┗━╸╹ ╹┗━╸╹┗╸╹ ╹┗━╸

source = ./execs.conf
source = ./design.conf
source = ./animations.conf
source = ./layout.conf
source = ./misc.conf
source = ./input.conf
source = ./binds.conf
source = ./rules.conf
