exec-once = pipewire
exec-once = pipewire-pulse
exec-once = wireplumber
exec-once = lxqt-policykit-agent
exec-once = dbus-update-activation-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=wlroots
exec-once = /usr/libexec/xdg-desktop-portal
exec-once = /usr/libexec/xdg-desktop-portal-wlr
exec-once = swww-daemon
